//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terminals.Connection {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedValues_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedValues_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Terminals.Connection.LocalizedValues_en", typeof(LocalizedValues_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Manager.
        /// </summary>
        internal static string CaptureManager {
            get {
                return ResourceManager.GetString("CaptureManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Icons.
        /// </summary>
        internal static string CaptureManager_ViewStyle_LargeIcons {
            get {
                return ResourceManager.GetString("CaptureManager_ViewStyle_LargeIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string CaptureManager_ViewStyle_List {
            get {
                return ResourceManager.GetString("CaptureManager_ViewStyle_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Icons.
        /// </summary>
        internal static string CaptureManager_ViewStyle_SmallIcons {
            get {
                return ResourceManager.GetString("CaptureManager_ViewStyle_SmallIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string CaptureManager_ViewStyle_Title {
            get {
                return ResourceManager.GetString("CaptureManager_ViewStyle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Root Folder.
        /// </summary>
        internal static string CaputureManager_Capture_CaptureManagerLayout_CaptureRootFolderName {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaptureManagerLayout_CaptureRootFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Multiple Items.
        /// </summary>
        internal static string CaputureManager_Capture_CaptureManagerLayout_ConfirmCaptionDeleteMultipleItems {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaptureManagerLayout_ConfirmCaptionDeleteMultipleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Item.
        /// </summary>
        internal static string CaputureManager_Capture_CaptureManagerLayout_ConfirmCaptionDeleteSingleItem {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaptureManagerLayout_ConfirmCaptionDeleteSingleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete these {0} files?.
        /// </summary>
        internal static string CaputureManager_Capture_CaptureManagerLayout_ConfirmDeleteMultipleFiles {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaptureManagerLayout_ConfirmDeleteMultipleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this file?.
        /// </summary>
        internal static string CaputureManager_Capture_CaptureManagerLayout_ConfirmDeleteSingleFile {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaptureManagerLayout_ConfirmDeleteSingleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this folder?.
        /// </summary>
        internal static string CaputureManager_Capture_CaptureManagerLayout_ConfirmDeleteSingleFolder {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaptureManagerLayout_ConfirmDeleteSingleFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Folder?.
        /// </summary>
        internal static string CaputureManager_Capture_CaptureManagerLayout_DeleteFolder {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaptureManagerLayout_DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder &quot;{0}&quot; contains {1} files..
        /// </summary>
        internal static string CaputureManager_Capture_CaptureManagerLayout_Directory {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaptureManagerLayout_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder &quot;{0}&quot; contains {1} directories..
        /// </summary>
        internal static string CaputureManager_Capture_CaptureManagerLayout_Files {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaptureManagerLayout_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New folder name.
        /// </summary>
        internal static string CaputureManager_Capture_CaptureManagerLayout_NewFolder {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaptureManagerLayout_NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post selected images to Flickr.
        /// </summary>
        internal static string CaputureManager_Capture_CaptureManagerLayout_PostToFlickr {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaptureManagerLayout_PostToFlickr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All items have been queued for upload to Flickr.  Once the upload has been completed you will be notified..
        /// </summary>
        internal static string CaputureManager_Capture_CaptureManagerLayout_PostToFlickr_Information {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaptureManagerLayout.PostToFlickr_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to post {0} images to your Flickr account?.
        /// </summary>
        internal static string CaputureManager_Capture_CaptureManagerLayout_PostToFlickr_Question {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaptureManagerLayout.PostToFlickr_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must first select a screen capture to upload..
        /// </summary>
        internal static string CaputureManager_Capture_CaptureManagerLayout_PostToFlickr_Warning {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaptureManagerLayout.PostToFlickr_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error uploading your screen shots to Flickr..
        /// </summary>
        internal static string CaputureManager_Capture_CaptureManagerLayout_SendToFlickr_Error {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaptureManagerLayout.SendToFlickr_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All images have been uploaded to Flickr..
        /// </summary>
        internal static string CaputureManager_Capture_CaptureManagerLayout_SendToFlickr_Information {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaptureManagerLayout.SendToFlickr_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy_MM_dd_hh_mm_ss.
        /// </summary>
        internal static string CaputureManager_Capture_CaputureManager {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaputureManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.comments.
        /// </summary>
        internal static string CaputureManager_Capture_CommentsFileName {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CommentsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to delete the screenshot..
        /// </summary>
        internal static string CaputureManager_Capture_Delete {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to move the screenshot..
        /// </summary>
        internal static string CaputureManager_Capture_Move_Error {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.Move_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %TITLE% screenshot.
        /// </summary>
        internal static string CaputureManager_Capture_PostToFlickr {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.PostToFlickr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be so kind to connect to Flickr via %TITLE% before you are able to post (Menu &quot;Tools&quot; ... &quot;Options&quot; ... &quot;Screen Capture&quot; ... &quot;Flickr&quot;)..
        /// </summary>
        internal static string CaputureManager_Capture_PostToFlickr_Error {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.PostToFlickr_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen capture failed..
        /// </summary>
        internal static string CaputureManager_Capture_ScreenCapture_Capture {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.ScreenCapture.Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\\{1}.{2:D2}.{3}.
        /// </summary>
        internal static string CaputureManager_Capture_ScreenCapture_Format1 {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.ScreenCapture_Format1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\\{1}.{2}.
        /// </summary>
        internal static string CaputureManager_Capture_ScreenCapture_Format2 {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.ScreenCapture_Format2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print failed..
        /// </summary>
        internal static string CaputureManager_Capture_ScreenCapture_Print {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.ScreenCapture.Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Speichern des Bild nach [{0}] im Format [{1}] schlug fehl.\n{2}.
        /// </summary>
        internal static string CaputureManager_Capture_ScreenCapture_Save {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.ScreenCapture.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on disconnecting from the capture manager..
        /// </summary>
        internal static string Connections_CaputureManagerConnection_Disconnect_Error {
            get {
                return ResourceManager.GetString("Connections.CaputureManagerConnection.Disconnect_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading TreeView item image..
        /// </summary>
        internal static string Connections_ConnectionImageHandler_LoadImage {
            get {
                return ResourceManager.GetString("Connections.ConnectionImageHandler.LoadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, %TITLE% was unable to create the connection. Try again or check the log for more information..
        /// </summary>
        internal static string Connections_ConnectionManager_CreateConnection {
            get {
                return ResourceManager.GetString("Connections.ConnectionManager.CreateConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable protocols for {0} plugin.
        /// </summary>
        internal static string EnableProtocolOptionPanel_Text {
            get {
                return ResourceManager.GetString("EnableProtocolOptionPanel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} options.
        /// </summary>
        internal static string OptionPanel_Text {
            get {
                return ResourceManager.GetString("OptionPanel.Text", resourceCulture);
            }
        }
    }
}
