//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terminals.Connection {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedValues_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedValues_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Terminals.Connection.LocalizedValues_de", typeof(LocalizedValues_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildverwaltungsmanager.
        /// </summary>
        internal static string CaptureManager {
            get {
                return ResourceManager.GetString("CaptureManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Große Bilder.
        /// </summary>
        internal static string CaptureManager_ViewStyle_LargeIcons {
            get {
                return ResourceManager.GetString("CaptureManager_ViewStyle_LargeIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste.
        /// </summary>
        internal static string CaptureManager_ViewStyle_List {
            get {
                return ResourceManager.GetString("CaptureManager_ViewStyle_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kleine Bilder.
        /// </summary>
        internal static string CaptureManager_ViewStyle_SmallIcons {
            get {
                return ResourceManager.GetString("CaptureManager_ViewStyle_SmallIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titelansicht.
        /// </summary>
        internal static string CaptureManager_ViewStyle_Title {
            get {
                return ResourceManager.GetString("CaptureManager_ViewStyle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schnappschussordner.
        /// </summary>
        internal static string CaputureManager_Capture_CaptureManagerLayout_CaptureRootFolderName {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaptureManagerLayout_CaptureRootFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mehrere Elemente löschen.
        /// </summary>
        internal static string CaputureManager_Capture_CaptureManagerLayout_ConfirmCaptionDeleteMultipleItems {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaptureManagerLayout_ConfirmCaptionDeleteMultipleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element löschen.
        /// </summary>
        internal static string CaputureManager_Capture_CaptureManagerLayout_ConfirmCaptionDeleteSingleItem {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaptureManagerLayout_ConfirmCaptionDeleteSingleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie diese Dateien tatsächlich {0} löschen?.
        /// </summary>
        internal static string CaputureManager_Capture_CaptureManagerLayout_ConfirmDeleteMultipleFiles {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaptureManagerLayout_ConfirmDeleteMultipleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie diese Datei wirklich löschen?.
        /// </summary>
        internal static string CaputureManager_Capture_CaptureManagerLayout_ConfirmDeleteSingleFile {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaptureManagerLayout_ConfirmDeleteSingleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie diesen Ordner wirklich löschen?.
        /// </summary>
        internal static string CaputureManager_Capture_CaptureManagerLayout_ConfirmDeleteSingleFolder {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaptureManagerLayout_ConfirmDeleteSingleFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordner löschen?.
        /// </summary>
        internal static string CaputureManager_Capture_CaptureManagerLayout_DeleteFolder {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaptureManagerLayout_DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Verzeichnis &quot;{0}&quot; enthält {1} Dateien..
        /// </summary>
        internal static string CaputureManager_Capture_CaptureManagerLayout_Directory {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaptureManagerLayout_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Verzeichnis &quot;{0}&quot; enthält {1} Ordner..
        /// </summary>
        internal static string CaputureManager_Capture_CaptureManagerLayout_Files {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaptureManagerLayout_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuer Verzeichnisname.
        /// </summary>
        internal static string CaputureManager_Capture_CaptureManagerLayout_NewFolder {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaptureManagerLayout_NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgewählte Bilder auf Flickr hochladen.
        /// </summary>
        internal static string CaputureManager_Capture_CaptureManagerLayout_PostToFlickr {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaptureManagerLayout_PostToFlickr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Bilder wurden für den Übertragungsvorgang an Flickr gereiht. Sobald der Vorgang abgeschlossen ist werden Sie notifiziert..
        /// </summary>
        internal static string CaputureManager_Capture_CaptureManagerLayout_PostToFlickr_Information {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaptureManagerLayout.PostToFlickr_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind Sie sicher, dass Sie {0} Bilder auf Ihren Flickr-Bereich hochladen wollen?.
        /// </summary>
        internal static string CaputureManager_Capture_CaptureManagerLayout_PostToFlickr_Question {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaptureManagerLayout.PostToFlickr_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte selektieren Sie Bilder damit diese hochgeladen werden können..
        /// </summary>
        internal static string CaputureManager_Capture_CaptureManagerLayout_PostToFlickr_Warning {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaptureManagerLayout.PostToFlickr_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es gab einen Fehler ihre Bilder in Flickr hochzuladen..
        /// </summary>
        internal static string CaputureManager_Capture_CaptureManagerLayout_SendToFlickr_Error {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaptureManagerLayout.SendToFlickr_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Bilder wurden erfolgreich in Flickr hochgeladen..
        /// </summary>
        internal static string CaputureManager_Capture_CaptureManagerLayout_SendToFlickr_Information {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaptureManagerLayout.SendToFlickr_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy_MM_dd_hh_mm_ss.
        /// </summary>
        internal static string CaputureManager_Capture_CaputureManager {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CaputureManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.Kommentare.
        /// </summary>
        internal static string CaputureManager_Capture_CommentsFileName {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.CommentsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Löschen des Bildes..
        /// </summary>
        internal static string CaputureManager_Capture_Delete {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Verschieben des Bildes..
        /// </summary>
        internal static string CaputureManager_Capture_Move_Error {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.Move_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild von %TITLE%.
        /// </summary>
        internal static string CaputureManager_Capture_PostToFlickr {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.PostToFlickr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte melden Sie sich via %TITLE% (Menü &quot;Werkzeuge&quot; ... &quot;Optionen&quot; ... &quot;Screen Capture&quot; ... &quot;Flickr&quot;) an bevor Sie posten können..
        /// </summary>
        internal static string CaputureManager_Capture_PostToFlickr_Error {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.PostToFlickr_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilderstellung von der aktiven %TITLE%verbindung schlug fehl..
        /// </summary>
        internal static string CaputureManager_Capture_ScreenCapture_Capture {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.ScreenCapture.Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\\{1}.{2:D2}.{3}.
        /// </summary>
        internal static string CaputureManager_Capture_ScreenCapture_Format1 {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.ScreenCapture_Format1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\\{1}.{2}.
        /// </summary>
        internal static string CaputureManager_Capture_ScreenCapture_Format2 {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.ScreenCapture_Format2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Druckvorgang schlug fehl..
        /// </summary>
        internal static string CaputureManager_Capture_ScreenCapture_Print {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.ScreenCapture.Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving image to [{0}] in format [{1}] failed.\n{2}.
        /// </summary>
        internal static string CaputureManager_Capture_ScreenCapture_Save {
            get {
                return ResourceManager.GetString("CaputureManager.Capture.ScreenCapture.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Trennen der Verbindung zum Bildverwaltungsmanager..
        /// </summary>
        internal static string Connections_CaputureManagerConnection_Disconnect_Error {
            get {
                return ResourceManager.GetString("Connections.CaputureManagerConnection.Disconnect_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Laden des TreeView-Element-Bildes..
        /// </summary>
        internal static string Connections_ConnectionImageHandler_LoadImage {
            get {
                return ResourceManager.GetString("Connections.ConnectionImageHandler.LoadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %TITLE% war leider nicht im Stande eine Verbindung aufzubauen. Versuchen Sie es erneut oder überpfürfen Sie bitte die Logdatei um nähere Informationen zu erhalten..
        /// </summary>
        internal static string Connections_ConnectionManager_CreateConnection {
            get {
                return ResourceManager.GetString("Connections.ConnectionManager.CreateConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protokolle für {0}-Plugin aktivieren.
        /// </summary>
        internal static string EnableProtocolOptionPanel_Text {
            get {
                return ResourceManager.GetString("EnableProtocolOptionPanel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}-Optionen.
        /// </summary>
        internal static string OptionPanel_Text {
            get {
                return ResourceManager.GetString("OptionPanel.Text", resourceCulture);
            }
        }
    }
}
