[assembly: System.Reflection.AssemblyTitle("Rug.Cmd")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Reflection.AssemblyDescription("")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Reflection.AssemblyCopyright("Copyright \x00a9 Rugland 2009")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.1")]
[assembly: System.Reflection.AssemblyCompany("Rugland")]
[assembly: System.Reflection.AssemblyProduct("Rug.Cmd")]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.InteropServices.Guid("88864a39-a326-4917-99ba-8fb0fad56158")]

