//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rpx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rpx.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress .Net Executables. .
        /// </summary>
        internal static string App_AboutText {
            get {
                return ResourceManager.GetString("App_AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   - Compress your .Net assembly for faster download.
        ///  - High ZIP compression with no unpack library overhead.
        ///  - Bundle multiple assemblys into a single distibution.
        ///  - Works for Windows Forms and Console Applications.
        ///  - Create a toolkit application that is a composite of mulitiple 
        ///    assemblys accessable via a menu.   
        ///  - Persist your assembly info so that you don&apos;t get into version hell.
        ///
        ///&lt;t:9&gt;Notes on assembly load process:
        ///The order of the locations that .Net will look for assemblys tha [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string App_AboutTextLong {
            get {
                return ResourceManager.GetString("App_AboutTextLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rugland Digital Systems
        ///http://www.ruglandrecords.com/rds/
        ///
        ///Copyright (C) 2008 - 2018 Phill Tew.
        /// </summary>
        internal static string App_CreditsText {
            get {
                return ResourceManager.GetString("App_CreditsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses Ionic.Zip for recompression.
        ///http://www.codeplex.com/DotNetZip
        ///
        ///Inspired by UPX (the Ultimate Packer for eXecutables)
        ///Markus F.X.J. Oberhumer, László Molnár &amp; John F. Reiser
        ///http://upx.sourceforge.net/.
        /// </summary>
        internal static string App_LegalText {
            get {
                return ResourceManager.GetString("App_LegalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rugland Packer for (.Net) eXecutables.
        /// </summary>
        internal static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this argument to use the assembly info from a source file.
        ///
        ///If the /Toolkit argument is defined then you must supply this argument.  
        ///
        ///If neither the /Toolkit or this option is defined then an attempt will be
        ///made to retrive the info from the assembly at the location specified in the
        ///&lt;exec file&gt; argument via reflection..
        /// </summary>
        internal static string Arg_AssemblyInfoPath_Help {
            get {
                return ResourceManager.GetString("Arg_AssemblyInfoPath_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssemblyInfo.
        /// </summary>
        internal static string Arg_AssemblyInfoPath_Key {
            get {
                return ResourceManager.GetString("Arg_AssemblyInfoPath_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssemblyInfo.cs.
        /// </summary>
        internal static string Arg_AssemblyInfoPath_Name {
            get {
                return ResourceManager.GetString("Arg_AssemblyInfoPath_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path of a AssemblyInfo.cs code file to use.
        /// </summary>
        internal static string Arg_AssemblyInfoPath_ShortHelp {
            get {
                return ResourceManager.GetString("Arg_AssemblyInfoPath_ShortHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        internal static string Arg_AssemblyInfoPath_Symbol {
            get {
                return ResourceManager.GetString("Arg_AssemblyInfoPath_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates errors compatible with MS VisualStudio.
        /// </summary>
        internal static string Arg_BuildSwitch_Help {
            get {
                return ResourceManager.GetString("Arg_BuildSwitch_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        internal static string Arg_BuildSwitch_Key {
            get {
                return ResourceManager.GetString("Arg_BuildSwitch_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build mode.
        /// </summary>
        internal static string Arg_BuildSwitch_ShortHelp {
            get {
                return ResourceManager.GetString("Arg_BuildSwitch_ShortHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output as a console or forms application, if not defined then the the value is derived from assembly supplyed in the &lt;exec file&gt; argument..
        /// </summary>
        internal static string Arg_ConsoleSwitch_Help {
            get {
                return ResourceManager.GetString("Arg_ConsoleSwitch_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        internal static string Arg_ConsoleSwitch_Key {
            get {
                return ResourceManager.GetString("Arg_ConsoleSwitch_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output as a console or forms application.
        /// </summary>
        internal static string Arg_ConsoleSwitch_ShortHelp {
            get {
                return ResourceManager.GetString("Arg_ConsoleSwitch_ShortHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c.
        /// </summary>
        internal static string Arg_ConsoleSwitch_Symbol {
            get {
                return ResourceManager.GetString("Arg_ConsoleSwitch_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This comes at a small cost to the assembly code size..
        /// </summary>
        internal static string Arg_Decorate_Help {
            get {
                return ResourceManager.GetString("Arg_Decorate_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorate.
        /// </summary>
        internal static string Arg_Decorate_Key {
            get {
                return ResourceManager.GetString("Arg_Decorate_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorate.
        /// </summary>
        internal static string Arg_Decorate_Name {
            get {
                return ResourceManager.GetString("Arg_Decorate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorate the console output of the resulting assembly.
        /// </summary>
        internal static string Arg_Decorate_ShortHelp {
            get {
                return ResourceManager.GetString("Arg_Decorate_ShortHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of additional assemblys to be bundled into the resulting executable.
        ///See additional notes on assembly load order by using the /?? switch.
        /// </summary>
        internal static string Arg_FileList_Help {
            get {
                return ResourceManager.GetString("Arg_FileList_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to additional assemblies.
        /// </summary>
        internal static string Arg_FileList_Name {
            get {
                return ResourceManager.GetString("Arg_FileList_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This helps protect your assemblys from unwanted unpacking or inspection by
        ///a third party.
        ///
        ///If the optional password is supplyed then the resource will be encrypted and
        ///only accessable by supplying the password as the fist argument when running 
        ///the application.
        ///
        ///If this switch is not supplyed then applications like WindowsExplore and
        ///WinRar will register the compressed assembly as a archive file and may give 
        ///options to the user for unpacking it.
        ///
        ///&lt;t:7&gt;This comes at a small cost to the final size [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Arg_Hide_Help {
            get {
                return ResourceManager.GetString("Arg_Hide_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string Arg_Hide_Key {
            get {
                return ResourceManager.GetString("Arg_Hide_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        internal static string Arg_Hide_Name {
            get {
                return ResourceManager.GetString("Arg_Hide_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide and protect compressed assemblys.
        /// </summary>
        internal static string Arg_Hide_ShortHelp {
            get {
                return ResourceManager.GetString("Arg_Hide_ShortHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assembly icon cannot be compressed so be careful and monitor its size. .
        /// </summary>
        internal static string Arg_IconPath_Help {
            get {
                return ResourceManager.GetString("Arg_IconPath_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string Arg_IconPath_Key {
            get {
                return ResourceManager.GetString("Arg_IconPath_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon.
        /// </summary>
        internal static string Arg_IconPath_Name {
            get {
                return ResourceManager.GetString("Arg_IconPath_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path of the icon to use on the resulting assembly.
        /// </summary>
        internal static string Arg_IconPath_ShortHelp {
            get {
                return ResourceManager.GetString("Arg_IconPath_ShortHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i.
        /// </summary>
        internal static string Arg_IconPath_Symbol {
            get {
                return ResourceManager.GetString("Arg_IconPath_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this argument if you what to compile to a spacific location.
        ///If this argument is not supplied then the default &lt;exec file&gt; argument will be used.
        /// </summary>
        internal static string Arg_OutputPath_Help {
            get {
                return ResourceManager.GetString("Arg_OutputPath_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string Arg_OutputPath_Key {
            get {
                return ResourceManager.GetString("Arg_OutputPath_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to output.
        /// </summary>
        internal static string Arg_OutputPath_Name {
            get {
                return ResourceManager.GetString("Arg_OutputPath_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit full path of the executable to create.
        /// </summary>
        internal static string Arg_OutputPath_ShortHelp {
            get {
                return ResourceManager.GetString("Arg_OutputPath_ShortHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o.
        /// </summary>
        internal static string Arg_OutputPath_Symbol {
            get {
                return ResourceManager.GetString("Arg_OutputPath_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this switch if defined then any command line arguments supplyed when
        ///executing the resulting assembly will be passed on. .
        /// </summary>
        internal static string Arg_PassArgsSwitch_Help {
            get {
                return ResourceManager.GetString("Arg_PassArgsSwitch_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PassArgs.
        /// </summary>
        internal static string Arg_PassArgsSwitch_Key {
            get {
                return ResourceManager.GetString("Arg_PassArgsSwitch_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass command line arguments.
        /// </summary>
        internal static string Arg_PassArgsSwitch_ShortHelp {
            get {
                return ResourceManager.GetString("Arg_PassArgsSwitch_ShortHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p.
        /// </summary>
        internal static string Arg_PassArgsSwitch_Symbol {
            get {
                return ResourceManager.GetString("Arg_PassArgsSwitch_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full or relitive path to a executable file to be compressed.
        ///Unless the /Toolkit argument is defined then it will be the location of the resulting toolkit..
        /// </summary>
        internal static string Arg_PathString_Help {
            get {
                return ResourceManager.GetString("Arg_PathString_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec file.
        /// </summary>
        internal static string Arg_PathString_Name {
            get {
                return ResourceManager.GetString("Arg_PathString_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable file to be compressed or the name of the resulting toolkit if /T is defined.
        /// </summary>
        internal static string Arg_PathString_ShortHelp {
            get {
                return ResourceManager.GetString("Arg_PathString_ShortHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t display messages about every action.
        /// </summary>
        internal static string Arg_QuietSwitch_Help {
            get {
                return ResourceManager.GetString("Arg_QuietSwitch_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiet.
        /// </summary>
        internal static string Arg_QuietSwitch_Key {
            get {
                return ResourceManager.GetString("Arg_QuietSwitch_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiet mode.
        /// </summary>
        internal static string Arg_QuietSwitch_ShortHelp {
            get {
                return ResourceManager.GetString("Arg_QuietSwitch_ShortHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this argument to create composite toolkit from multiple assemblys.
        ///
        ///The supplyed value should be a comma seperated value (CSV) string in the
        ///format &quot;[Tool Name]:[Tool Path],[Tool Name2]:[Tool Path2],..&quot;
        ///
        ///Where [Tool Name] is the name of the menu item within the composite toolkit
        ///assembly and [Tool Path] is the full path to the tool assembly..
        /// </summary>
        internal static string Arg_Toolkit_Help {
            get {
                return ResourceManager.GetString("Arg_Toolkit_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Arg_Toolkit_Key {
            get {
                return ResourceManager.GetString("Arg_Toolkit_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tools csv.
        /// </summary>
        internal static string Arg_Toolkit_Name {
            get {
                return ResourceManager.GetString("Arg_Toolkit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A CSV of tools in the format &quot;[Tool Name]:[Tool Path],..&quot;.
        /// </summary>
        internal static string Arg_Toolkit_ShortHelp {
            get {
                return ResourceManager.GetString("Arg_Toolkit_ShortHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this argument to specify the level of detail RPX outputs whilst it is running..
        /// </summary>
        internal static string Arg_Verbose_Help {
            get {
                return ResourceManager.GetString("Arg_Verbose_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose.
        /// </summary>
        internal static string Arg_Verbose_Key {
            get {
                return ResourceManager.GetString("Arg_Verbose_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message verbosity level.
        /// </summary>
        internal static string Arg_Verbose_ShortHelp {
            get {
                return ResourceManager.GetString("Arg_Verbose_ShortHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When +w warning will be reported as errors.
        ///When -w warnings will not be reported at all.
        ///
        ///This switch is to be used in conjunction with the /build switch..
        /// </summary>
        internal static string Arg_WarningsAsErrors_Help {
            get {
                return ResourceManager.GetString("Arg_WarningsAsErrors_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Arg_WarningsAsErrors_Key {
            get {
                return ResourceManager.GetString("Arg_WarningsAsErrors_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings are errors.
        /// </summary>
        internal static string Arg_WarningsAsErrors_ShortHelp {
            get {
                return ResourceManager.GetString("Arg_WarningsAsErrors_ShortHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string AssemblyInfo_Company {
            get {
                return ResourceManager.GetString("AssemblyInfo_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string AssemblyInfo_Configuration {
            get {
                return ResourceManager.GetString("AssemblyInfo_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string AssemblyInfo_Copyright {
            get {
                return ResourceManager.GetString("AssemblyInfo_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture.
        /// </summary>
        internal static string AssemblyInfo_Culture {
            get {
                return ResourceManager.GetString("AssemblyInfo_Culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string AssemblyInfo_Description {
            get {
                return ResourceManager.GetString("AssemblyInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileVersion.
        /// </summary>
        internal static string AssemblyInfo_FileVersion {
            get {
                return ResourceManager.GetString("AssemblyInfo_FileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string AssemblyInfo_Product {
            get {
                return ResourceManager.GetString("AssemblyInfo_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trademark.
        /// </summary>
        internal static string AssemblyInfo_Trademark {
            get {
                return ResourceManager.GetString("AssemblyInfo_Trademark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string AssemblyInfo_Version {
            get {
                return ResourceManager.GetString("AssemblyInfo_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly info is from a source file.
        /// </summary>
        internal static string Compiler_AssemblyInfoFromFile {
            get {
                return ResourceManager.GetString("Compiler_AssemblyInfoFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly info has been reflected.
        /// </summary>
        internal static string Compiler_AssemblyInfoHasBeenReflected {
            get {
                return ResourceManager.GetString("Compiler_AssemblyInfoHasBeenReflected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application target is {0}.
        /// </summary>
        internal static string Compiler_AssemblyTarget {
            get {
                return ResourceManager.GetString("Compiler_AssemblyTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backing up existing assembly..
        /// </summary>
        internal static string Compiler_BackupAsm {
            get {
                return ResourceManager.GetString("Compiler_BackupAsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors building {0}.
        /// </summary>
        internal static string Compiler_BuildErrors {
            get {
                return ResourceManager.GetString("Compiler_BuildErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete junked files..
        /// </summary>
        internal static string Compiler_CannotDeleteJunkFiles {
            get {
                return ResourceManager.GetString("Compiler_CannotDeleteJunkFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning up junk files..
        /// </summary>
        internal static string Compiler_CleaningJunkFiles {
            get {
                return ResourceManager.GetString("Compiler_CleaningJunkFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation failed ({0} errors).
        /// </summary>
        internal static string Compiler_CompileFailed {
            get {
                return ResourceManager.GetString("Compiler_CompileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling final assembly.
        /// </summary>
        internal static string Compiler_CompileStart {
            get {
                return ResourceManager.GetString("Compiler_CompileStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling.
        /// </summary>
        internal static string Compiler_Compiling {
            get {
                return ResourceManager.GetString("Compiler_Compiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the console.
        /// </summary>
        internal static string Compiler_ConsoleApplication {
            get {
                return ResourceManager.GetString("Compiler_ConsoleApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the console.
        ///As the &apos;+C&apos; argument has not been specfied and the informtion could not be obtained from the PE head.
        /// </summary>
        internal static string Compiler_DefaultApplication {
            get {
                return ResourceManager.GetString("Compiler_DefaultApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete temperary archive file..
        /// </summary>
        internal static string Compiler_DeleteTempArchive {
            get {
                return ResourceManager.GetString("Compiler_DeleteTempArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving from Resources. Tried &apos;{0}&apos;\n{1}.
        /// </summary>
        internal static string Compiler_ErrorGettingResource {
            get {
                return ResourceManager.GetString("Compiler_ErrorGettingResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to windows forms.
        /// </summary>
        internal static string Compiler_FormsApplication {
            get {
                return ResourceManager.GetString("Compiler_FormsApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Cryptography code.
        /// </summary>
        internal static string Compiler_IncludeCryptographyCode {
            get {
                return ResourceManager.GetString("Compiler_IncludeCryptographyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Disguise code.
        /// </summary>
        internal static string Compiler_IncludeDisguiseCode {
            get {
                return ResourceManager.GetString("Compiler_IncludeDisguiseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junking backup assembly..
        /// </summary>
        internal static string Compiler_JunkingBackupAsm {
            get {
                return ResourceManager.GetString("Compiler_JunkingBackupAsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Compiler_Options {
            get {
                return ResourceManager.GetString("Compiler_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing assembly(s)..
        /// </summary>
        internal static string Compiler_PackingAsm {
            get {
                return ResourceManager.GetString("Compiler_PackingAsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying recompressor.
        /// </summary>
        internal static string Compiler_Recompressor {
            get {
                return ResourceManager.GetString("Compiler_Recompressor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource with the path &apos;{0}&apos; does not exist.
        /// </summary>
        internal static string Compiler_ResourceDoesNotExist {
            get {
                return ResourceManager.GetString("Compiler_ResourceDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No resource has been defined.
        /// </summary>
        internal static string Compiler_ResourceNotDefined {
            get {
                return ResourceManager.GetString("Compiler_ResourceNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring backup assembly..
        /// </summary>
        internal static string Compiler_RestoreBackupAsm {
            get {
                return ResourceManager.GetString("Compiler_RestoreBackupAsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Toolkit.
        /// </summary>
        internal static string Compiler_Toolkit {
            get {
                return ResourceManager.GetString("Compiler_Toolkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Tools.
        /// </summary>
        internal static string Compiler_Tools {
            get {
                return ResourceManager.GetString("Compiler_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load assembly.
        /// </summary>
        internal static string Compiler_UnableToLoadAsm {
            get {
                return ResourceManager.GetString("Compiler_UnableToLoadAsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot decrypt file &apos;{0}&apos; as it does not exist.
        /// </summary>
        internal static string Decrypt_ErrorPathDoesNotExist {
            get {
                return ResourceManager.GetString("Decrypt_ErrorPathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot disguise file &apos;{0}&apos; as it does not exist.
        /// </summary>
        internal static string Disguise_ErrorPathDoesNotExist {
            get {
                return ResourceManager.GetString("Disguise_ErrorPathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot encrypt file &apos;{0}&apos; as it does not exist.
        /// </summary>
        internal static string Encrypt_ErrorPathDoesNotExist {
            get {
                return ResourceManager.GetString("Encrypt_ErrorPathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted size.
        /// </summary>
        internal static string Encypt_EncryptedSize {
            get {
                return ResourceManager.GetString("Encypt_EncryptedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original size.
        /// </summary>
        internal static string Encypt_OriginalSize {
            get {
                return ResourceManager.GetString("Encypt_OriginalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Encypt_Password {
            get {
                return ResourceManager.GetString("Encypt_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salt.
        /// </summary>
        internal static string Encypt_Salt {
            get {
                return ResourceManager.GetString("Encypt_Salt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        internal static string Encypt_Strength {
            get {
                return ResourceManager.GetString("Encypt_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec file must be supplyed.
        /// </summary>
        internal static string Error_0101 {
            get {
                return ResourceManager.GetString("Error_0101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source file &apos;{0} does not exist.
        /// </summary>
        internal static string Error_0102 {
            get {
                return ResourceManager.GetString("Error_0102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressed size is bigger than the initial size.
        ///Was the assembly allready compressed?.
        /// </summary>
        internal static string Error_0103 {
            get {
                return ResourceManager.GetString("Error_0103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must supply a output path.
        /// </summary>
        internal static string Error_0104 {
            get {
                return ResourceManager.GetString("Error_0104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with tool definition &apos;{0}&apos;, you must supply a tool name. 
        ///The expected format is &quot;Name:Path&quot;.
        /// </summary>
        internal static string Error_0105 {
            get {
                return ResourceManager.GetString("Error_0105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must supply a AssemblyInfo file path.
        /// </summary>
        internal static string Error_0106 {
            get {
                return ResourceManager.GetString("Error_0106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported subsystem type: &apos;{0}&apos;.
        /// </summary>
        internal static string Error_0107 {
            get {
                return ResourceManager.GetString("Error_0107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reflecting assembly information.
        /// </summary>
        internal static string Error_0108 {
            get {
                return ResourceManager.GetString("Error_0108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Icon Group reserved id.
        /// </summary>
        internal static string Error_0109 {
            get {
                return ResourceManager.GetString("Error_0109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Icon Group type id.
        /// </summary>
        internal static string Error_0110 {
            get {
                return ResourceManager.GetString("Error_0110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while extracting icon from PE file .
        /// </summary>
        internal static string Error_0111 {
            get {
                return ResourceManager.GetString("Error_0111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while reading the PE header.
        /// </summary>
        internal static string Error_0112 {
            get {
                return ResourceManager.GetString("Error_0112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disguised.
        /// </summary>
        internal static string Hide_Disguised {
            get {
                return ResourceManager.GetString("Hide_Disguised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted.
        /// </summary>
        internal static string Hide_Encrypted {
            get {
                return ResourceManager.GetString("Hide_Encrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protection.
        /// </summary>
        internal static string Hide_Protection {
            get {
                return ResourceManager.GetString("Hide_Protection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packed size.
        /// </summary>
        internal static string Package_CompressedSize {
            get {
                return ResourceManager.GetString("Package_CompressedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression.
        /// </summary>
        internal static string Package_Compression {
            get {
                return ResourceManager.GetString("Package_Compression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacked size.
        /// </summary>
        internal static string Package_FilesTotalSize {
            get {
                return ResourceManager.GetString("Package_FilesTotalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Summary.
        /// </summary>
        internal static string Package_SummaryTitle {
            get {
                return ResourceManager.GetString("Package_SummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying package protection.
        /// </summary>
        internal static string Protection_SummaryTitle {
            get {
                return ResourceManager.GetString("Protection_SummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recompression.
        /// </summary>
        internal static string Recompressor_Compression {
            get {
                return ResourceManager.GetString("Recompressor_Compression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inital.
        /// </summary>
        internal static string Recompressor_Inital {
            get {
                return ResourceManager.GetString("Recompressor_Inital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid.
        /// </summary>
        internal static string Recompressor_Invalid {
            get {
                return ResourceManager.GetString("Recompressor_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recompressed.
        /// </summary>
        internal static string Recompressor_Recompressed {
            get {
                return ResourceManager.GetString("Recompressor_Recompressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found icon.
        /// </summary>
        internal static string Reflection_FoundIconResource {
            get {
                return ResourceManager.GetString("Reflection_FoundIconResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sizes and or colour depths.
        /// </summary>
        internal static string Reflection_FoundNImageLayers {
            get {
                return ResourceManager.GetString("Reflection_FoundNImageLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No icon was found.
        /// </summary>
        internal static string Reflection_NoIconFound {
            get {
                return ResourceManager.GetString("Reflection_NoIconFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read the PE Header of the assembly &apos;{0}&apos;.
        /// </summary>
        internal static string Reflector_CouldNotReadPE {
            get {
                return ResourceManager.GetString("Reflector_CouldNotReadPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final size.
        /// </summary>
        internal static string Text_FinalSize {
            get {
                return ResourceManager.GetString("Text_FinalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Summary.
        /// </summary>
        internal static string Text_FinalSummary {
            get {
                return ResourceManager.GetString("Text_FinalSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon file size.
        /// </summary>
        internal static string Text_IconFileSize {
            get {
                return ResourceManager.GetString("Text_IconFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string Text_Invalid {
            get {
                return ResourceManager.GetString("Text_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of original size.
        /// </summary>
        internal static string Text_OfOriginalSize {
            get {
                return ResourceManager.GetString("Text_OfOriginalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total compression.
        /// </summary>
        internal static string Text_OverallCompression {
            get {
                return ResourceManager.GetString("Text_OverallCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup overhead.
        /// </summary>
        internal static string Text_StartupOverhead {
            get {
                return ResourceManager.GetString("Text_StartupOverhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total size.
        /// </summary>
        internal static string Text_TotalSize {
            get {
                return ResourceManager.GetString("Text_TotalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncompressed size.
        /// </summary>
        internal static string Text_UncompressedSize {
            get {
                return ResourceManager.GetString("Text_UncompressedSize", resourceCulture);
            }
        }
    }
}
