//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace Terminals.ExportImport.Import
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class Connection {

        private string descriptionField;

        private string credentialsField;

        private string audioField;

        private string autoSizeField;

        private string consoleField;

        private string inheritCredentialsField;

        private string localDrivesField;

        private string printerField;

        private string resolutionXField;

        private string resolutionYField;

        private string serialField;

        private string smartCardField;

        private string portField;

        private string separateWindowField;

        private string clipboardField;

        private string colorDepthField;

        private string keyboardModeField;

        private string performanceFlagsField;

        private string bitmapCachingField;

        private string nameField;

        private string serverNameField;

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Credentials {
            get {
                return this.credentialsField;
            }
            set {
                this.credentialsField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Audio {
            get {
                return this.audioField;
            }
            set {
                this.audioField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AutoSize {
            get {
                return this.autoSizeField;
            }
            set {
                this.autoSizeField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Console {
            get {
                return this.consoleField;
            }
            set {
                this.consoleField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InheritCredentials {
            get {
                return this.inheritCredentialsField;
            }
            set {
                this.inheritCredentialsField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LocalDrives {
            get {
                return this.localDrivesField;
            }
            set {
                this.localDrivesField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Printer {
            get {
                return this.printerField;
            }
            set {
                this.printerField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ResolutionX {
            get {
                return this.resolutionXField;
            }
            set {
                this.resolutionXField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ResolutionY {
            get {
                return this.resolutionYField;
            }
            set {
                this.resolutionYField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Serial {
            get {
                return this.serialField;
            }
            set {
                this.serialField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SmartCard {
            get {
                return this.smartCardField;
            }
            set {
                this.smartCardField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SeparateWindow {
            get {
                return this.separateWindowField;
            }
            set {
                this.separateWindowField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Clipboard {
            get {
                return this.clipboardField;
            }
            set {
                this.clipboardField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ColorDepth {
            get {
                return this.colorDepthField;
            }
            set {
                this.colorDepthField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KeyboardMode {
            get {
                return this.keyboardModeField;
            }
            set {
                this.keyboardModeField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PerformanceFlags {
            get {
                return this.performanceFlagsField;
            }
            set {
                this.performanceFlagsField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BitmapCaching {
            get {
                return this.bitmapCachingField;
            }
            set {
                this.bitmapCachingField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string ServerName {
            get {
                return this.serverNameField;
            }
            set {
                this.serverNameField = value;
            }
        }
    }
}